name: k6

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      datadog-agent:
        image: datadog/agent:7.67.0@sha256:9b9f7d3a817ae50bd0e3e15de9089ffee184893854e9956d0fba4ab28a329ffd
        env:
          # https://docs.datadoghq.com/containers/docker/?tab=standard#environment-variables
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_HOSTNAME: github.com
          DD_ENV: ${{ github.ref_name }}
          # https://docs.datadoghq.com/opentelemetry/interoperability/otlp_ingest_in_the_agent/?tab=docker
          DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT: 0.0.0.0:4317
        ports:
          - 4317:4317
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v4.0.1
        with:
          aqua_version: v2.53.3

      - run: k6 run src/http-get.ts
        env:
          # https://grafana.com/docs/k6/latest/results-output/real-time/opentelemetry/
          K6_OUT: experimental-opentelemetry
          K6_OTEL_GRPC_EXPORTER_INSECURE: true
          K6_OTEL_METRIC_PREFIX: k6.

      # Wait for the Datadog Agent to flush the metrics.
      - run: sleep 10
