name: k6

on:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      datadog-agent:
        image: datadog/agent:7.63.2
        env:
          # https://docs.datadoghq.com/containers/docker/?tab=standard#environment-variables
          DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DD_HOSTNAME: none
          # https://docs.datadoghq.com/opentelemetry/interoperability/otlp_ingest_in_the_agent/?tab=docker
          DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT: 0.0.0.0:4318
        ports:
          - 4318:4318
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build

      - uses: aquaproj/aqua-installer@v3.1.1
        with:
          aqua_version: v2.45.0

      - run: k6 run lib/http-get.js
        env:
          # https://grafana.com/docs/k6/latest/results-output/real-time/opentelemetry/
          K6_OUT: experimental-opentelemetry
          K6_OTEL_EXPORTER_TYPE: http
          K6_OTEL_HTTP_EXPORTER_INSECURE: true
          K6_OTEL_HTTP_EXPORTER_ENDPOINT: localhost:4318
      - run: sleep 10
