name: test

on:
  pull_request:
    paths:
      - src/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/test.yaml
  push:
    branches:
      - main
    paths:
      - src/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/test.yaml

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm lint --fix
      - run: pnpm format
      - run: pnpm build
      - uses: int128/update-generated-files-action@v2
